# Generated by Django 4.2.2 on 2023-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
